### ISSUE TITLE
PPGW使用mode=socks5每次虚拟机冷启动后均无法访问网站

### ISSUE THREAD

**Issue by LR7SKQUO** [kkkgo/PaoPaoGateWay#11]
如题，冷启动后，再web ui中能看到proxies中有一个socks项，rules中也能看到Match socks。但本地电脑通过浏览器访问路由到PPGW的网站均提示ERR_CONNECTION_TIMED_OUT。若此时若修改ppgw.ini的mode为其他任意值，待PPGW读取后，再修改ppgw.ini的mode为socks5，再等PPGW读取配置后，电脑访问这些网站就OK。
在问题发生时，访问网站，PPGW的web ui Conns中看不到对应的条目，后台终端屏幕也看不到相关信息，似乎只有DNS的访问记录：
![image](https://github.com/kkkgo/PaoPaoGateWay/assets/4255110/ed708532-d216-42b3-bcb2-f7693b3bbad3)
问题“解决”后，访问网站，PPGW web ui能看到对应访问记录：
![image](https://github.com/kkkgo/PaoPaoGateWay/assets/4255110/3b666180-0fbb-4459-a285-2eefe56bee7b)
请帮忙看一下是bug还是我的设置问题，谢谢！

网络拓扑如下，所有EXSI虚拟机均直通网卡
![image](https://github.com/kkkgo/PaoPaoGateWay/assets/4255110/574ffeec-7e1e-40c3-b07c-e223d4aba7d0)
iKuai：开启web服务7890端口（ppgw.ini），已设置静态路由7.0.0.0/8的网关为192.168.2.250，DHCP服务分配的DNS为192.168.2.253与192.168.2.251
PPDNS-*：undocked（alpine虚拟机直接运行），仅修改init.sh中 `if [ "$MEMSIZE" -gt 2000 ]; then` 为 `if [ "$MEMSIZE" -gt 1500 ]; then` 。debug.sh输出结果如附件。force_forward_list.txt见附件。
[dnsdebug.txt](https://github.com/kkkgo/PaoPaoGateWay/files/12045442/dnsdebug.txt)
[force_forward_list.txt](https://github.com/kkkgo/PaoPaoGateWay/files/12045447/force_forward_list.txt)
Openwrt：仅作为openclash的运行环境，未将其设置为旁路由。
PPGW：配置如附件。
[ppgw.txt](https://github.com/kkkgo/PaoPaoGateWay/files/12045464/ppgw.txt)

**Comment by kkkgo** [comment]
你是不是用docker定制了带sniff的iso

**Comment by kkkgo** [comment]
冷启动是指什么情况？可以再描述一下吗

**Comment by kkkgo** [comment]
冷启动是不是指其他部分都正常运作的情况下，首次打开ppgw虚拟机后，无法正常工作？还是其他部分未开启之前就启动了ppgw

**Comment by kkkgo** [comment]
在无法正常工作的情况下，进行以下测试，以便定位问题，谢谢！  
```
1. 使用本地电脑查询被代理域名的解析结果。比如
nslookup github.com
2. 进入ppdns的环境，使用以下命令查询解析结果，比如
dig github.com @127.0.0.1 -p5303
3. 在局域网任意linux终端上尝试使用ppgw的代理端口看看是否能用，比如
curl -d"info" --socks5-hostname 192.168.2.250:1080 https://ip.03k.org
```

**Comment by kkkgo** [comment]
好的，根据你的提供的描述，我测试下再回复您。

**Comment by kkkgo** [comment]
麻烦在无法工作的时候，再进行以下测试：
```
1. ping代理的域名看看是否ping通。
ping github.com
2. 跟踪被代理域名的路由。
tracert github.com
``

**Comment by kkkgo** [comment]
在ppgw虚拟机上，按下回车，输入以下命令，查看nft状态。
```
nft list ruleset
````

**Comment by kkkgo** [comment]
虚拟机内执行`nft_tcp.sh`后看看是否正常代理。

**Comment by kkkgo** [comment]
此时执行以下命令，看看是否有输出。
```
ps | grep -v "grep" | grep "/etc/config/clash"
```

**Comment by kkkgo** [comment]
看起来逻辑上应该不会出问题，但在加载clash后却忽略了nft规则的添加。但我测试了socks模式也正常。你可以把ppgw的启动过程日志录制下来吗？可以使用GifCam工具

**Comment by kkkgo** [comment]
嗯，看到了日志确实没有触发添加规则，有可能是虚拟机平台结果差异，我稍后编译一个iso给你测试下。

**Comment by kkkgo** [comment]
测试下这个镜像是否正常工作。
[paopao-gateway-x86-64-test202307141330.zip](https://github.com/kkkgo/PaoPaoGateWay/files/12046489/paopao-gateway-x86-64-test202307141330.zip)

**Comment by kkkgo** [comment]
此问题在最新release中修复。https://github.com/kkkgo/PaoPaoGateWay/releases/tag/20230714-288a1db

**Comment by kkkgo** [comment]
另外对于你的网络拓扑，我可能有点好奇或者建议：  
1. 如果你想直接监听宿主网络，可以使用docker的host模式。使用docker并不会损失性能，可以方便更新或者重建服务。  
2. openwrt的功能可能与ppgw重合，你可以使用yaml或者suburl模式来完成openclash的功能。（如有协议不支持，你可以使用docker定制更换核心）

**Comment by kkkgo** [comment]
使用subconverter等程序可以转换合并订阅。如果是基于force_forward_list来分流，GEOIP应该用不上。如果是基于非大陆IP分流，可以使用ppdns的AUTO_FORWARD功能，ppdns会自行更新IP库。关于GEOIP在ppgw中的实际作用，可以参见此链接：  
https://github.com/kkkgo/PaoPaoGateWay/discussions/6#discussioncomment-6112812
