### ISSUE TITLE
自定义ppgwurl.ini后能拉取ppgw.ini但不能拉取yaml文件(被改成默认端口7889了）

### ISSUE THREAD

**Issue by Pzf874** [kkkgo/PaoPaoGateWay#116]
自定义ppgw的ISO中放入了ppgwurl.ini，指定ppgw.ini的位置在我的web服务器上如：
http://192.168.10.253:88/ppgw.ini

ppgw.ini中定义了
mode=yaml
yamlfile="custom.yaml"

启动ppgw后，确实拉取了
http://192.168.10.253:88/ppgw.ini
然后拉取custom.yaml的时候，还是从7889端口拉，导致失败（我的web服务器并没有开7889）
...fail get http://192.168.10.253:7889/custom.yaml : connect refused.....

能否改进一下，拉取任何文件时，ppgwurl.ini中的“ppgw.ini"前部分全部保留作为起始点，比如
http://mysite:myport/mysubpath/ppgw.ini
那么所有文件都从”http://mysite:myport/mysubpath/“ 开始拉

**Comment by Pzf874** [comment]
补充一下：目前我的绕过方式是改：mode=suburl,然后
suburl="http://192.168.10.253:88/custom.yaml"
但是这个方式的yaml更新时间很慢

**Comment by kkkgo** [comment]
‘subtime则指定刷新订阅的时间间隔，单位可以是m（分钟），h（小时）或者d（天），默认值为1d’
