### ISSUE TITLE
网关启动后代理规则没有

### ISSUE THREAD

**Issue by qiaoyun680** [kkkgo/PaoPaoGateWay#124]
网关启动以后，服务器下载成功,在 Web UI 界面可以看到服务器信息，通过 global 也可以用了，只是规则里头居然啥都没有，这究竟正不正常呢？订阅链接当中是有着分流规则的。另外，ui 面板可不可以进行替换呀？感谢大佬！

**Comment by kkkgo** [comment]
看文档，你设置fast_node=yes就是没有规则。
