### ISSUE TITLE
PaoPaoGateWay使用过程断流

### ISSUE THREAD

**Issue by cococle** [kkkgo/PaoPaoGateWay#131]
内核切换到M内核，协议用的是VLESS的，使用过程经常断流，比如谷歌浏览器正常使用，停顿一会，浏览器就不能访问国外网站了，必须重启谷歌浏览器才能，YOUTUBE也是经常视频一直在转圈圈。

**Comment by kkkgo** [comment]
https://github.com/kkkgo/PaoPaoGateWay/discussions/92

**Comment by cococle** [comment]
已经加上参数，但是还是会出现断流。

**Comment by kkkgo** [comment]
检查路由器规则，比如ROS的ddos规则。

**Comment by kkkgo** [comment]
https://github.com/kkkgo/PaoPaoGateWay/discussions/92#discussioncomment-9245711
还是跟上面贴的连接一样，检查是否被分配了其他DNS地址或者IPv6地址，对应被代理的域名是否会被解析出ipv6地址，尝试定制嗅探sniff=yes的镜像，最后设置静态IP地址，网关填写ppgw的IP，DNS填写ppgw的DNS，测试是否会断流，如果不会，可以看看流量记录是否请求了第三方DNS。

爱快另参考 https://github.com/kkkgo/PaoPaoGateWay/discussions/26

**Comment by cococle** [comment]
按照你说的我也去测试了，都还是断流，最后我把XRAY切换为1.8.18旧版本，好像就没事了

**Comment by cococle** [comment]
最终结果，我使用的是爱快路由，必须把DNS劫持到paopaodns，劫持后全部正常了。
