### ISSUE TITLE
自定义ppgw的ISO中放入了ppgwurl.ini，域名对应的是香港IP拉取失败!

### ISSUE THREAD

**Issue by cococle** [kkkgo/PaoPaoGateWay#132]
自定义ppgw的ISO中放入了ppgwurl.ini，指定ppgw.ini的位置在我的web服务器上如：
http://域名(绑定的是香港IP)/ppgw.ini,启动界面报错DNS解析失败。

**Comment by kkkgo** [comment]
没有日志。

**Comment by cococle** [comment]
已解决，要把域名强制走cn才能解析到
