### ISSUE TITLE
DNS泄露

### ISSUE THREAD

**Issue by cococle** [kkkgo/PaoPaoGateWay#136]
切换M内核，https://whoer.net/zh检测出现DNS泄露，怎么解决？

**Comment by cococle** [comment]
主路由是爱快，只做了静态路由设置，PPDNS如下：
docker run -d --net=host -it \
--name FrayunDNS \
-v /home/mydata:/data \
-e DNS_SERVERNAME=FrayunDNS \
-e UPDATE=daily \
-e CNAUTO=yes \
-e CNFALL=yes \
-e CN_TRACKER=yes \
-e SOCKS5=192.168.1.52:1080  \
-e SERVER_IP=192.168.1.53  \
-e DNSPORT=53  \
-e IPV6=no \
-e USE_HOSTS=no \
-e HTTP_FILE=yes  \
-e CUSTOM_FORWARD=192.168.1.52:53  \
-e AUTO_FORWARD=yes   \
-e AUTO_FORWARD_CHECK=yes \
-e USE_MARK_DATA=yes \
-e ADDINFO=yes \
-e SHUFFLE=yes \
-e EXPIRED_FLUSH=yes \
-e TZ=Asia/Shanghai \
--restart unless-stopped \
public.ecr.aws/sliamb/paopaodns

**Comment by kkkgo** [comment]
两方面找原因，首先你确定你客户端使用的是paopaodns而不是套娃的上游，其次ppgw的配置文件正确配置DNS。

**Comment by cococle** [comment]
没有任何套娃，ppgw没有配置dns

**Comment by cococle** [comment]
而且泄露的全是国外的不知明的ip，有很多个国家

**Comment by kkkgo** [comment]
你可能对DNS泄漏有误解。。。列表只要没有中国的就不算泄漏

**Comment by cococle** [comment]
![Uploading IMG_5413.png…]()

**Comment by kkkgo** [comment]
你的图片上传失败了。

**Comment by cococle** [comment]
![IMG_5413](https://github.com/user-attachments/assets/ad1ea292-e7e0-462c-9672-5fd19cac18bd)

**Comment by kkkgo** [comment]
列表没有中国啊

**Comment by cococle** [comment]
这样不算泄露吗？不是很懂，有时候检测又一个都没有

**Comment by kkkgo** [comment]
vpn提供商的DNS泄漏检测仅仅检测你是否在用他家的vpn，用了就不算泄漏。
没有用他家vpn的就把你向他域名查询的IP给你列出来。他自家的VPN去查就不列出来。
你想让他查到不泄露把他域名拦截了不发起查询就不泄漏，没什么高科技含量。

**Comment by cococle** [comment]
明白了，谢谢
