### ISSUE TITLE
说说使用感受

### ISSUE THREAD

**Issue by gukey** [kkkgo/PaoPaoGateWay#2]
体验了一下，没有成功，说实话，clash 的使用门槛还是比较高的，设置较为繁琐，同步了配置文件，没成功代理，目前觉得 xray reality协议是个不错的选择，因为支持最新加密，用passwall使用简单。

**Comment by kkkgo** [comment]
Clash官方开源版本不支持xray reality吧，你可以替换Meta核心：https://github.com/MetaCubeX/Clash.Meta/issues/398

**Comment by kkkgo** [comment]
最新版本可以使用docker定制ISO镜像，你可以替换clash核心：https://github.com/kkkgo/PaoPaoGateWay#%E4%BD%BF%E7%94%A8docker%E5%AE%9A%E5%88%B6iso%E9%95%9C%E5%83%8Fppwgiso  
另外你可以登录Web端看看日志，或者看看虚拟机本地终端也有日志。其实`ppgw.ini`的配置项相当少，只是说明文档写的太详细，没有成功的话，具体你是什么模式的出站呢？是否已经配置了静态路由了呢？
