### ISSUE TITLE
ppgw无法连接特定节点（DNS问题）

### ISSUE THREAD

**Issue by lr7skquo** [kkkgo/PaoPaoGateWay#20]
近期观察到个人使用的某个机场，其节点速度在ppgw永远是超时。单独使用该机场节点，观察ppgw console输出，测速(fast_node=check)时提示connection reset by peer.
![image](https://github.com/kkkgo/PaoPaoGateWay/assets/4255110/961a120f-9512-47f3-8e33-c5c6ebc90018)

使用fast_node=yes，全部节点测速失败，错误信息503 service unavailable.
![image](https://github.com/kkkgo/PaoPaoGateWay/assets/4255110/1ef23b60-0b25-4cd9-921c-420af016f38b)

节点信息如附件（已打码）。
[test1.yaml.txt](https://github.com/kkkgo/PaoPaoGateWay/files/12509902/test1.yaml.txt)

通过电脑端clash verge确认，至少"SG 流媒体O1"、"SG 流媒体O2"、"JP 流媒体O1"、"JP 流媒体O2"、"US 流媒体O1"、"US 流媒体O2"是可以正常使用并测速OK的。

**Comment by kkkgo** [comment]
在web面板是否正常显示节点，web面板能否测速？

**Comment by kkkgo** [comment]
是最新的版本吗？是上面有问题的节点不能测速还是按钮都不能测速？面板的测速按钮应该是没问题的，可以清空下浏览器缓存或者换个浏览器试试？
另外你是手写配置还是suburl模式？是用机场给的订阅连接吗？

**Comment by kkkgo** [comment]
贴一下ppgw配置

**Comment by kkkgo** [comment]
suburltest@proton.me
你的机场订阅导入clash verge也无法使用是吗？如果是的话，你可以提供一份clash verge可以使用但ppgw无法使用的yaml配置我测试下

**Comment by kkkgo** [comment]
好的。我今天有空的时候测试下，再看看问题出在哪里。

**Comment by kkkgo** [comment]
经过你提供的订阅测试，定位到问题在于你的机场提供的节点服务器，DNS解析对不同区域使用了不同的策略，并且仅在使用境内DNS的时候才能获取到正确的服务器入口，由于ppgw对节点解析均使用境外可信任数据（如果使用默认推荐的PaoPaoDNS 5304的话），因此造成无法连接的效果。此操作可能机场是有别的安全上考虑，但实际上会造成很多无法使用的问题（比如部分地区DNS解析结果不正确，DNS分区域解析总不能100%准确）
你可以使用https://ping.chinaz.com/ 来测试看你服务器节点域名的解析结果在全球是否一致。
要验证这个问题，你可以在ppgw的可信任DNS设置项修改为223.5.5.5（dns_ip=223.5.5.5、dns_port=53）等国内DNS来测试。
注意，使用国内DNS会泄漏你的DNS查询记录。

**Comment by kkkgo** [comment]
直接使用53端口的话需注意如果节点非中转而是直连的话会造成死循环。比如订阅地址的IP在境外或者节点IP在境外，53端口会转发到ppgw。如果出现这些问题，请手动调整force_nocn列表。

**Comment by kkkgo** [comment]
针对这个场景，新版本新增了`dns_burn`选项功能。https://github.com/kkkgo/PaoPaoGateWay/releases

**Comment by hussion** [comment]
@kkkgo 同碰到了这个问题，请教一下：

1. 如果不想使用`fast_node`(因为梯子各个节点速度不是太稳定， 自动换来换去意义不大)
2. 经过测试自用梯子server域名对应的解析ip均为国内ip
3. 我这种情况，把ppgw的可信任ip设置为阿里云/腾讯云等国内dns ip，是否可行 ？

**Comment by kkkgo** [comment]
> @kkkgo 同碰到了这个问题，请教一下：
> 
> 1. 如果不想使用`fast_node`(因为梯子各个节点速度不是太稳定， 自动换来换去意义不大)
> 2. 经过测试自用梯子server域名对应的解析ip均为国内ip
> 3. 我这种情况，把ppgw的可信任ip设置为阿里云/腾讯云等国内dns ip，是否可行 ？

不使用vpn类（如wg，openvpn）协议的话dns仅用于节点解析，除非节点在境外解析不一样，一般不用考虑这个问题。
如果单纯是节点全都在境内的需求，直接用paopaodns的53端口就好了，国内IP本来就不会返回fakeIP，境外的可以自己加一下force_dnscrypt_list。

**Comment by hussion** [comment]
> > @kkkgo 同碰到了这个问题，请教一下：
> > 
> > 1. 如果不想使用`fast_node`(因为梯子各个节点速度不是太稳定， 自动换来换去意义不大)
> > 2. 经过测试自用梯子server域名对应的解析ip均为国内ip
> > 3. 我这种情况，把ppgw的可信任ip设置为阿里云/腾讯云等国内dns ip，是否可行 ？
> 
> 不使用vpn类（如wg，openvpn）协议的话dns仅用于节点解析，除非节点在境外解析不一样，一般不用考虑这个问题。 如果单纯是节点全都在境内的需求，直接用paopaodns的53端口就好了，国内IP本来就不会返回fakeIP，境外的可以自己加一下force_dnscrypt_list。

使用的是clash类订阅，mode=yaml，自定义配置；目前问题是dns_ip设置的为ppdns的5304端口，节点的域名全部解析不了。
